services:
  node1:
    container_name: node1
    image: openthread/environment
    networks:
      ot-net:
        ipv6_address: "fd42:1337::2"
    ports:
      - "9001:9001/udp"
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    stdin_open: true
    tty: true

  node2:
    container_name: node2
    image: openthread/environment
    networks:
      ot-net:
        ipv6_address: "fd42:1337::3"
    ports:
      - "9002:9002/udp"
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    stdin_open: true
    tty: true

networks:
  ot-net:
    external: true